<?php
/**
 * it is same structure as the provided sample from BoxalinoClientProject_BoxalinoIntegration::api/catalog/product/list/item.phtml
 * which is based of the default Magento2 product grid item view
 *
 * NOTE: the GET($propertyName) is accessing the property directly
 * THE ATTRIBUTES MUST EXIST ON THE BX-HIT ELEMENT
 * IT WILL THROW AN EXCEPTION OTHERWISE, IN ORDER TO ASSIST WITH DEVELOPMENT
 *
 * ALWAYS CHECK YOUR API RESPONSE IN ORDER TO DESIGN THE TEMPLATES ACCORDINGLY
 *
 * @var $block Boxalino\RealTimeUserExperience\Block\Api\Item
 * @var $item \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\AccessorInterface | \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Hit
 */
?>
<?php
/** @var  \ArrayIterator $bxAttributes required tracking HTML attributes */
$bxAttributes = $block->getBxAttributes();
$item = $block->getApiItem();
?>

<li class="item product product-item <?php /* @escapeNotVerified */ echo  $bxAttributes->getClass(); ?>""
    <?php foreach($bxAttributes as $attribute):?>
        <?php /* @escapeNotVerified */ echo $attribute->getName()?>="<?php /* @escapeNotVerified */ echo $attribute->getValue();?>"
    <?php endforeach;?>
    >
    <div class="product-item-info" data-container="product-list">
        <?php  $_nameStripped = $block->stripTags($item->get("title"), null, true); ?>
        <a href="<?= $block->escapeUrl($item->get("id")) ?>"
           class="product photo product-item-photo"
           tabindex="-1">
            <img src="<?php echo $item->get("id");?>" alt="<?php echo $_nameStripped;?>"/>
        </a>
        <div class="product details product-item-details">
            <strong class="product name product-item-name">
                <a class="product-item-link"
                   href="<?= $block->escapeUrl($item->get("id")) ?>">
                    <?= /* @noEscape */ $_nameStripped ?>
                </a>
            </strong>

            <div class="product description product-item-description">
                <p><?php echo $item->get("title");?></p>
                <a href="<?= $block->escapeUrl($item->get("id")) ?>"
                   title="<?= /* @noEscape */ $_nameStripped ?>"
                   class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
            </div>
        </div>
    </div>
</li>
