<?php
/**
 * Loads collection of facets from response
 *
 * (guidance model: Boxalino\RealTimeUserExperience\Model\Response\Content\ApiFacet)
 * The block & template is displayed as instructed by the API response
 * The filter properties (as defined in \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Facet)
 *
 * @var $block \Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\Navigation
 * @var $filter \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Facet
 */
?>
<?php $wrapOptions = false; ?>
<div class="block filter">
    <div class="block-title filter-title" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <strong><?= $block->escapeHtml(__('Shop By')) ?></strong>
    </div>

    <div class="block-content filter-content">
        <?= $block->getChildHtml("state"); ?>
        <?php if ($block->hasActiveFilters()) : ?>
            <div class="block-actions filter-actions">
                <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                    <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                </a>
            </div>
        <?php endif; ?>
        <?php $expandedFacets = $block->getExpandedFiltersConfiguration();?>
        <?php foreach ($block->getFilters() as $filter) : ?>
            <?php if ($filter->getValues()->count()) : ?>
                <?php if (!$wrapOptions) : ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                        <?php /* @escapeNotVerified */ echo __('Shopping Options') ?>
                    </strong>
                    <div class="filter-options" id="narrow-by-list" data-role="content"
                         data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active":<?= $expandedFacets;?>, "multipleCollapsible": true}}'>
                <?php $wrapOptions = true; endif; ?>
                <div data-role="collapsible" class="filter-options-item">
                    <div data-role="title" class="filter-options-title"><?= $block->escapeHtml(__($filter->getLabel())) ?></div>
                    <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($wrapOptions) : ?>
            </div>
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
        <?php endif; ?>
    </div>
</div>
<script>
    require([
        'jquery'
    ], function($) {
        $(".show-more-values").on('click', function () {
            var header = $(this);
            var content = header.parent().find('.hidden-items');
            content.slideToggle(500, function () {
                header.text(function () {
                    return content.is(":visible") ? "<?php echo __('less values');?>" : "<?php echo __('more values');?>";
                });
            });
        });
    });
</script>
