<?php
/**
 * Loads collection of facets from response
 *
 * (guidance model: Boxalino\RealTimeUserExperience\Model\Response\Content\ApiFacet)
 * The block & template is displayed as instructed by the API response
 * The use of a renderer-top is optional; the top-facets design can be directly included in the main template
 *
 * @var $block \Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\Navigation
 * @var $filter \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Facet
 */
?>
<?php foreach($block->getFilters() as $filter) :?>
    <?php if($filter->getValues()->count()):?>
        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer-top')->render($filter) ?></div>
    <?php endif;?>
<?php endforeach;?>
