<?php
/**
 * State renderer for a generic (select) facet
 * The sample template is being included via BoxalinoClientProject_BoxalinoIntegration::api/layered-navigation/state.phtml
 *
 * @var $block \Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\State
 * @var $filter \Boxalino\RealTimeUserExperience\Service\Api\Response\Accessor\Facet
 * @var $selectedValue \Boxalino\RealTimeUserExperience\Service\Api\Response\Accessor\FacetValue
 */
?>
<?php foreach($filter->getSelectedValues() as $selectedValue) :?>
    <li class="item">
        <span class="filter-label"><?= $block->escapeHtml(__($filter->getLabel())) ?></span>
        <span class="filter-value"><?= $block->escapeHtml($block->stripTags($selectedValue->getValue())) ?></span>
        <?php $currentFilterName = $block->escapeHtmlAttr(__($filter->getLabel()) . " " . $block->stripTags($selectedValue->getValue()));?>
        <a class="action remove" href="<?= $block->escapeUrl($selectedValue->getRemoveUrl()) ?>"
           title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName ?>">
            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
        </a>
    </li>
<?php endforeach;?>
