<?php
/**
 * State renderer for a range facet
 *
 * For the purpose of the integration sample:
 * 1. the range facet is discountedPrice, the currency is displayed as well
 * 2. the sample template is being included via Boxalino_RealTimeUserExperienceIntegration::api/layered-navigation/state.phtml
 *
 * @var $block \Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\State
 * @var $selectedValue \Boxalino\RealTimeUserExperience\Service\Api\Response\Accessor\FacetValue
 * @var $filter \Boxalino\RealTimeUserExperience\Service\Api\Response\Accessor\Facet
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<?php foreach($filter->getSelectedValues() as $selectedValue) :?>
    <li class="item">
        <span class="filter-label"><?= $block->escapeHtml(__($filter->getLabel())) ?></span>
        <span class="filter-value">
            <?php if($selectedValue->getMinSelectedValue() && !$selectedValue->getMaxSelectedValue()) :?>
                <?php /* @escapeNotVerified */ echo __('from') ?> <?= $block->escapeHtml($block->stripTags($priceHelper->currency($selectedValue->getMinSelectedValue())));?>
            <?php elseif($selectedValue->getMaxSelectedValue() && !$selectedValue->getMinSelectedValue()):?>
                <?php /* @escapeNotVerified */ echo __('to') ?> <?= $block->escapeHtml($block->stripTags($priceHelper->currency($selectedValue->getMaxSelectedValue())));?>
            <?php else:?>
                <?= $block->escapeHtml($block->stripTags($priceHelper->currency($selectedValue->getMinSelectedValue()))) . " - " . $block->escapeHtml($block->stripTags($priceHelper->currency($selectedValue->getMaxSelectedValue())));?>
            <?php endif;?>
        </span>
        <a class="action remove" href="<?= $block->escapeUrl($selectedValue->getRemoveUrl()) ?>"
           title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove')) . " " . $block->escapeHtmlAttr(__($filter->getLabel())) ?>">
            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
        </a>
    </li>
<?php endforeach;?>
