<?php
/**
 * Filter render using the Boxalino REST API response
 * (as seen in Magento_LayeredNavigation::layer/filter.phtml)
 * Includes the "more values" toggle logic (JS logic part of the BoxalinoClientProject_BoxalinoRealTimeUserExperienceIntegration::api/layered-navigation/layer/view.phtml)
 *
 * @var $block Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\Filter
 * @var $filterItem \Boxalino\RealTimeUserExperience\Service\Api\Response\Accessor\FacetValue
 * @var $filter \Boxalino\RealTimeUserExperience\Service\Api\Response\Accessor\Facet
 */
?>
<?php
$showCount = $block->getFilter()->isShowCounter();
$showedMoreLink = false;
$filter = $block->getFilter();
?>
<ol class="items">
    <?php foreach ($block->getFilter()->getValues() as $index => $filterItem) : ?>
        <?php if((!$filterItem->isShow() || $filter->getEnumDisplayMaxSize() < $index) && !$showedMoreLink):?>
            <?php $showedMoreLink = true; $more_values = __('more values');?>
                <li style="cursor:pointer" class="show-more-values"><?= /* @noEscape */ $more_values ?></li>
        <?php endif;?>
        <li class="item <?php echo $block->getFilter()->getVisualisation(); echo $filterItem->isSelected() == true ? ' selected':'';?>
            <?php echo ($filterItem->isShow() && $filter->getEnumDisplayMaxSize() >= $index)  ? '':' hidden-items';?>"
            style="<?php echo ($filterItem->isShow() && $filter->getEnumDisplayMaxSize() >= $index) ? "" : "display:none";?>">
            <?php if ($filterItem->getHitCount() > 0): ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getSelectUrl()) ?>">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($showCount): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getHitCount()?>
                            <span class="filter-count-label">
                                <?php if ($filterItem->getHitCount() == 1):?>
                                    <?php /* @escapeNotVerified */ echo __('item')?>
                                <?php else:?>
                                    <?php /* @escapeNotVerified */ echo __('items') ?>
                                <?php endif;?>
                            </span>
                        </span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($showCount): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getHitCount()?>
                        <span class="filter-count-label">
                            <?php if ($filterItem->getHitCount() == 1):?>
                                <?php /* @escapeNotVerified */ echo __('item')?>
                            <?php else:?>
                                <?php /* @escapeNotVerified */ echo __('items') ?>
                            <?php endif;?>
                        </span>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>

