<?php
/**
 * Filter renderer
 * Mock for the visualisation of different field types (this logic should be part of your renderer block)
 *
 * @var $block Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\Filter
 */
?>
<?php
// phpcs:disable Magento2.Security.IncludeFile.FoundIncludeFile
// phpcs:disable PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket
?>
<?php if($block->getFilter()->getVisualisation() == 'range' || $block->getFilter()->getField() == 'discountedPrice'): ?>
    <?php include ($block->getTemplateFile('BoxalinoClientProject_BoxalinoIntegration::api/layered-navigation/layer/filter/range.phtml')) ?>
<?php elseif($block->getFilter()->getVisualisation() == 'yesno'):?>
    <?php include ($block->getTemplateFile('BoxalinoClientProject_BoxalinoIntegration::api/layered-navigation/layer/filter/yesno.phtml')) ?>
<?php elseif($block->getFilter()->getField() == \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Facet::RTUX_API_FACET_CATEGORY):?>
    <?php include ($block->getTemplateFile('BoxalinoClientProject_BoxalinoIntegration::api/layered-navigation/layer/filter/category.phtml')) ?>
<?php elseif($block->getFilter()->getField() == \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Facet::RTUX_API_FACET_CATEGORIES):?>
    <?php include ($block->getTemplateFile('BoxalinoClientProject_BoxalinoIntegration::api/layered-navigation/layer/filter/category.phtml')) ?>
<?php else:?>
    <?php include ($block->getTemplateFile('BoxalinoClientProject_BoxalinoIntegration::api/layered-navigation/layer/filter/generic.phtml')) ?>
<?php endif;?>

