<?php
/**
 * Layered navigation state
 * Mock for the visualisation of different field types (this logic should be part of your renderer block)
 *
 * @var $filter \Boxalino\RealTimeUserExperienceApi\Service\Api\Response\Accessor\Facet
 * @var $block \Boxalino\RealTimeUserExperience\Block\LayeredNavigation\Layer\State
 */
?>
<?php $filters = $block->getActiveFilters() ?>
<?php if ($filters->count()) : ?>
    <div class="filter-current">
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-count="<?= /* @noEscape */ count($filters) ?>"><?= $block->escapeHtml(__('Now Shopping by')) ?></strong>
        <ol class="items">
            <?php foreach ($filters as $filter) : ?>
                <?php if($filter->getVisualisation()=='range' || $filter->getField()=='discountedPrice') :?>
                    <?php include ($block->getTemplateFile('Boxalino_RealTimeUserExperienceIntegration::api/layered-navigation/layer/state/range.phtml')) ?>
                <?php else:?>
                    <?php include ($block->getTemplateFile('Boxalino_RealTimeUserExperienceIntegration::api/layered-navigation/layer/state/generic.phtml')) ?>
                <?php endif;?>
            <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>
