<?php
/**
 * Template used to represent the product-wrapper for listing
 * sequence from vendor/magento/module-catalog/view/frontend/templates/product/list.phtml
 *
 * @var $block Boxalino\RealTimeUserExperience\Block\Catalog\Product\ListProduct
 */
?>

<?php $viewMode = $block->getMode();?>
<?php $bxAttributes = $block->getBxAttributes();?>

<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> <?php /* @escapeNotVerified */ echo  $bxAttributes->getClass(); ?>"
    <?php foreach($bxAttributes as $attribute):?>
        <?php /* @escapeNotVerified */ echo $attribute->getName()?>="<?php /* @escapeNotVerified */ echo $attribute->getValue();?>"
    <?php endforeach;?>
>
    <ol class="products list items product-items">
        <?php foreach($this->getBlocks() as $block):?>
            <?php $apiBlock = $this->getApiBlock($block);?>
            <?php if($apiBlock) : ?>
                <?php echo $apiBlock->toHtml();?>
            <?php endif; ?>
        <?php endforeach;?>
    </ol>
</div>
