<?php
/**
 * Template used to represent the product-wrapper for listing
 * sequence from vendor/magento/module-catalog/view/frontend/templates/product/list.phtml
 *
 * @var $block Boxalino\RealTimeUserExperience\Block\Catalog\Product\ListProduct
 */
?>

<?php $viewMode = $block->getMode();?>
<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> bx-narrative"
     data-bx-variant-uuid="<?php echo $this->getRtuxVariantUuid(); ?>"
     data-bx-narrative-name="products-list"
     data-bx-narrative-group-by="<?php echo $this->getRtuxGroupBy();?>">
    <ol class="products list items product-items">
        <?php foreach($this->getBlocks() as $block) :?>
            <?php echo $this->getApiBlock($block)->toHtml();?>
        <?php endforeach; ?>
    </ol>
</div>
