<?php
/**
 * Product list sorting options
 * As seen in Magento_Catalog::product/list/toolbar/sorter.phtml
 * (changes: the label access, the "direction" is removed as the sorting fields are joined with it)
 *
 * @var $block \Boxalino\RealTimeUserExperience\Block\Catalog\Product\ProductList\Sorting
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order->getLabel())) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
