<?php
/**
 * Autocomplete templates which are used by the the BoxalinoClientProject_BoxalinoIntegration/js/rtuxApiAutocompleteMixin
 * the template ID is set as parameter in the Boxalino Layout Block JSON schema
 *
 * The bx-attributes from the API response must be declared here
 */
?>
<script type="text/x-magento-template" id="rtux-product-template">
    <div class="<%- data.bxAttributes.class %>" data-bx-item-id="<%- data.bxAttributes.dataBxItemId %>">
        <a href="<%- data.selected_link[0] %>">
            <li class="<%- data.class %> text_suggest_<%- data.index %>" role="option">
                <span class="product-image"><img src="<%- data.selected_image[0] %>"></span>
                <span class="product-name"><%- data.selected_title %></span>
                <span class="product-price">CHF <%- data.selected_list_price %></span>
            </li>
        </a>
    </div>
</script>

<script type="text/x-magento-template" id="rtux-suggestion-template">
    <ul class="<%- data.parentBxAttributes.class %>" data-bx-variant-uuid="<%- data.parentBxAttributes.dataBxVariantUuid %>" data-bx-narrative-name="<%- data.parentBxAttributes.dataBxNarrativeName %>" data-bx-narrative-group-by="<%- data.parentBxAttributes.dataBxNarrativeGroupBy %>">
        <li class="<%- data.bxAttributes.class %> <%- data.class %> <%- data.index %>" id="qs-option-<%- data.index %>" data-bx-item-id="<%- data.bxAttributes.dataBxItemId %>" data-bx-item-type="<%- data.bxAttributes.dataBxItemType %>" role="option">
            <span class="qs-option-name"><%- data.suggestion %></span>
            <span aria-hidden="true" class="amount"><%- data.totalHitCount %></span>
        </li>
    </ul>
</script>

<script type="text/x-magento-template" id="rtux-title-template">
    <% if (data.title) { %>
    <li><h4 class="suggestion-title"><%- data.title %></h4></li>
    <% } %>
</script>

<script type="text/x-magento-template" id="rtux-js-markup-template">
    <div class="<%- data.class %>" data-bx-variant-uuid="<%- data.dataBxVariantUuid %>" data-bx-narrative-name="<%- data.dataBxNarrativeName %>" data-bx-narrative-group-by="<%- data.dataBxNarrativeGroupBy %>">
</script>
